React `18.3.3`
karakum-team/types-kotlin pull request #13
Opened 2024-07-02 07:49 UTC by porotkin

cc @turansky, @aerialist7

2024-07-06 19:10 UTC, turansky requested changes

2024-07-06 19:10 UTC, turansky commented on react-kotlin/src/jsMain/kotlin/react/dom/html/ImgFetchPriority.kt
> +sealed external interface ImgFetchPriority {
Redundant?

2024-07-06 19:10 UTC, turansky commented on buildSrc/src/main/kotlin/karakum/react/MemberConverter.kt
> +        .removePrefix("   | ") // TODO: Check after multiline unions patch
Text  patch before conversion?

2024-07-06 19:22 UTC, porotkin commented on react-kotlin/src/jsMain/kotlin/react/dom/html/ImgFetchPriority.kt
> +sealed external interface ImgFetchPriority {
yep

2024-07-07 05:52 UTC, porotkin commented on buildSrc/src/main/kotlin/karakum/react/MemberConverter.kt
> +        .removePrefix("   | ") // TODO: Check after multiline unions patch
done

2024-07-08 07:01 UTC, porotkin commented on buildSrc/src/main/kotlin/karakum/common/Strings.kt
> +    .removeSurrounding("$quote")
"\""

2024-07-09 19:53 UTC, turansky requested changes

2024-07-09 19:53 UTC, turansky commented on buildSrc/src/main/kotlin/karakum/react/AutoComplete.kt
>  internal const val AUTO_COMPLETE = """
Is it used?

2024-07-09 20:05 UTC, porotkin commented on buildSrc/src/main/kotlin/karakum/react/AutoComplete.kt
>  internal const val AUTO_COMPLETE = """
yes
![Uploading image.png…]()

2024-07-09 20:08 UTC, porotkin commented on buildSrc/src/main/kotlin/karakum/react/UnionConverter.kt
> +internal fun String.withNormalizedUnions(): String {
no such thing anymore, outdated concern

2024-07-10 13:04 UTC, turansky approved these changes

2024-07-10 13:05 UTC, merged